Feat/domain validation normalization
rsksmart/rns-manager-react pull request #499
Opened 2023-03-02 10:42 UTC by LordCheta

2023-03-02 12:45 UTC, sergio-jara requested changes
I was checking this PR by running and after the name registration finished, I clicked in MANAGE and the site crashed.

2023-03-02 12:47 UTC, OnyekaIjeh commented
> I was checking this PR by running and after the name registration finished, I clicked in MANAGE and the site crashed.

Same.

2023-03-06 13:20 UTC, sergio-jara requested changes
![image](https://user-images.githubusercontent.com/6055676/223121381-f534dadc-e502-47a2-9308-f705b31f00bd.png)
just found this issue. fix before merge please.

2023-03-08 12:45 UTC, sergio-jara approved these changes

2023-03-08 12:45 UTC, merged