Fix/multiple manager issues
rsksmart/rns-manager-react pull request #526
Opened 2023-11-13 12:59 UTC by LordCheta

This PR fixes the following issues: 
[Activating "Multichain Addresses Resolver" doesn't look like working to the end user](https://rsklabs.atlassian.net/browse/RNS-459)

[Error while creating a subdomain setting a different owner](https://rsklabs.atlassian.net/browse/RNS-454)

2023-11-14 15:23 UTC, sergio-jara requested changes

2023-11-14 15:23 UTC, sergio-jara commented on src/app/tabs/newAdmin/addresses/containers/MigrateToMultiResolverContainer.js
> +    // debugger;
remove

2023-11-14 16:50 UTC, LordCheta commented on src/app/tabs/newAdmin/addresses/containers/MigrateToMultiResolverContainer.js
> +    // debugger;
good catch

2023-11-16 13:44 UTC, LordCheta commented
Fix introduced in a newer pr: https://github.com/rsksmart/rns-manager-react/pull/528

2023-11-16 13:44 UTC, closed without merging